apiVersion: v1
kind: Secret
metadata:
  name: acstgwm-secret
  namespace: acstgwm
type: Opaque
data:
  GOOGLE_CLIENT_ID: <base64-encoded-CLIENT-ID>
  GOOGLE_CLIENT_SECRET: <base64-encoded-CLIENT-SECRET>
  GMAIL_USERNAME: <base64-encoded-gamserviceaccount@acst.net>
  GMAIL_PASSWORD: <base64-encoded-aeac szbp adjp jbzd>
  DEEPSEEK_API_KEY: <base64-encoded-sk-656bbf19a58346a3a0e077d45b9d2260>
  GOOGLE_SERVICE_ACCOUNT_KEY_PATH: <base64-encoded-service-account.json-content>
  GOOGLE_SERVICE_ACCOUNT_USER: <base64-encoded-gamserviceaccount@acst.net>
