apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: argocd
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: marwenhm/backendimage:latest
          ports:
            - containerPort: 8089
          env:
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: MONGODB_URI
            - name: REDIS_HOST
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: REDIS_HOST
            - name: REDIS_PORT
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: REDIS_PORT
            - name: FRONTEND_URL
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: FRONTEND_URL
            - name: GOOGLE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: GOOGLE_CLIENT_ID
            - name: GOOGLE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: GOOGLE_CLIENT_SECRET
            - name: GOOGLE_REDIRECT_URI
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: GOOGLE_REDIRECT_URI
            - name: DEEPSEEK_API_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: DEEPSEEK_API_KEY
            - name: GMAIL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: GMAIL_USERNAME
            - name: GMAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: GMAIL_PASSWORD
            - name: GOOGLE_SERVICE_ACCOUNT_USER
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: GOOGLE_SERVICE_ACCOUNT_USER
          volumeMounts:
            - name: service-account
              mountPath: /config
              readOnly: true
          command:
            - java
            - -Dgoogle.service.account.key.location=file:/config/service-account.json
            - -jar
            - /app/ACST.jar
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          readinessProbe:
            httpGet:
              path: /health
              port: 8089
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8089
            initialDelaySeconds: 15
            periodSeconds: 20
      volumes:
        - name: service-account
          secret:
            secretName: google-service-account
