apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: argocd
spec:
  selector:
    app: backend
  ports:
    - port: 8089
      targetPort: 8089
      nodePort: 32583  # Pin to 32583
  type: NodePort
